name: Create post

on:
  schedule:
    # This runs at 07:00 IL Sun-Fri
    - cron: '0 4 * * 0-5'

  # Optional: Allow manual trigger
  workflow_dispatch:

jobs:
  run-api-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run Python Script
      env:
        # Add any API keys or sensitive credentials as environment variables
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: | 
        python JewishHistoryBot.py
        cat post.md >> $GITHUB_STEP_SUMMARY
        cat summary.md >> $GITHUB_STEP_SUMMARY